"""Generate a fully hashed requirements lock from the active environment."""

from __future__ import annotations

import argparse
import importlib.metadata
from pathlib import Path

import requests
from packaging.utils import canonicalize_name

EXCLUDED = {"education-erp-decision-intelligence", "pip"}


def installed_packages() -> list[tuple[str, str]]:
    packages = {
        (canonicalize_name(distribution.metadata["Name"]), distribution.version)
        for distribution in importlib.metadata.distributions()
        if distribution.metadata.get("Name")
        and canonicalize_name(distribution.metadata["Name"]) not in EXCLUDED
    }
    return sorted(packages)


def artifact_hashes(name: str, version: str) -> list[str]:
    response = requests.get(
        f"https://pypi.org/pypi/{name}/{version}/json",
        timeout=30,
    )
    response.raise_for_status()
    hashes = {
        artifact["digests"]["sha256"]
        for artifact in response.json()["urls"]
        if artifact.get("digests", {}).get("sha256")
    }
    if not hashes:
        raise RuntimeError(f"No published SHA-256 artifacts found for {name}=={version}")
    return sorted(hashes)


def render_lock() -> str:
    lines = [
        "# Generated by scripts/generate_hashed_lock.py.",
        "# Install with: python -m pip install --require-hashes -r requirements.lock",
        "",
    ]
    for name, version in installed_packages():
        hashes = artifact_hashes(name, version)
        lines.append(f"{name}=={version} \\")
        for index, digest in enumerate(hashes):
            suffix = " \\" if index < len(hashes) - 1 else ""
            lines.append(f"    --hash=sha256:{digest}{suffix}")
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    args.output.write_text(render_lock(), encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
